#! /bin/bash

# (c) Jm Weeger 2018

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# Copie de la source apt de Kubernetes
fcopy -M /etc/apt/sources.list.d/kubernetes.list

# add additional user account
if [ -n "$username" ]; then
    if ! $ROOTCMD getent passwd $username ; then
	$ROOTCMD adduser --disabled-login --gecos "$username user" $username
	$ROOTCMD usermod -p "$USERPW" $username
	userdir=$($ROOTCMD getent passwd "$username" | cut -d: -f6 )

	for g in $groups; do
	    $ROOTCMD adduser $username $g
	done
    fi
fi